config/routes.rb
Newstemweb::Application.routes.draw do

  resources :posts

  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'
  resources :lookups

  root to: "lookups#main"
  match "runspedestem" => "runstem#index", :as => "runstem", :via => "get"
  match "runspedestem/subsampling" => "runstem#subsamplingform", :as => "subsamplingform", :via => "get"
  match "runspedestem/subsampling" => "runstem#subsampling", :as => "subsampling", :via => "post"
  match "runspedestem/generatesettings" => "runstem#generatesettingsform", :as => "generatesettingsform", :via => "get"
  match "runspedestem/generatesettings" => "runstem#generatesettings", :as => "generatesettings", :via => "post"
  match "runspedestem/discovery" => "runstem#discoveryform", :as => "discoveryform", :via => "get"
  match "runspedestem/discovery" => "runstem#discovery", :as => "discovery", :via => "post"

  match "runspedestem/validation" => "runstem#validationform", :as => "validationform", :via => "get"
  match "runspedestem/validation" => "runstem#validation", :as => "validation", :via => "post"

  
  match "runspedestem/cleantrees" => "runstem#cleantreesform", :as => "cleantreesform", :via => "get"
  match "runspedestem/cleantrees" => "runstem#cleantrees", :as => "cleantrees", :via => "post"

  match "/contact" => "lookups#contact", :as => "contact", :via => "get"

  match "contact/genhelp" => "lookups#genhelpform", :as => "genhelpform_contact", :via => "get"
  match "contact/genhelp" => "lookups#genhelp", :as => "genhelp_contact", :via => "post"

  match "contact/techhelp" => "lookups#techhelpform", :as => "techhelpform_contact", :via => "get"
  match "contact/techhelp" => "lookups#techhelp", :as => "techhelp_contact", :via => "post"

end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  before_action :set_lookup, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:edit, :update, :destroy, :new, :create]
    
  include ApplicationHelper
  def main 
      handle_lookup("main")
  end

  def contact 
      handle_lookup("contact")
  end

  def handle_lookup(name)
      @lookup = Lookup.where(name: name).first
      if @lookup
          @content = @lookup.content
      else
          @content = "Nothing here yet."
      end
      respond_to do |format|
          format.html { render name}
          format.json { render text: @content } 
      end
  end

  def mailhelp (dest_email)
    # carstens_email = APP_CONFIG["carstens_email"]
    useremail = params[:from]
    subject = params[:subject]
    body = params[:body]
    RunstemMailer.help_email(useremail, dest_email, subject, body).deliver
    flash_notice "email has been sent from #{useremail}"
    redirect_to contact_path
  end

  def genhelp
      mailhelp APP_CONFIG["carstens_email"]
  end

  def techhelp
      mailhelp APP_CONFIG["kim_email"]
  end

  # GET /lookups
  # GET /lookups.json
  def index
    @lookups = Lookup.all
  end

  # GET /lookups/1
  # GET /lookups/1.json
  def show
  end

  # GET /lookups/new
  def new
    @lookup = Lookup.new
  end

  # GET /lookups/1/edit
  def edit
      session[:return_to] = request.referer
  end


  # POST /lookups
  # POST /lookups.json
  def create
    @lookup = Lookup.new(lookup_params)
    respond_to do |format|
      if @lookup.save
        format.html { redirect_to @lookup, notice: 'Lookup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lookup }
      else
        format.html { render action: 'new' }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lookups/1
  # PATCH/PUT /lookups/1.json
  def update
    respond_to do |format|
      if @lookup.update(lookup_params)
        format.html { redirect_to session.delete(:return_to), notice: 'Lookup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1
  # DELETE /lookups/1.json
  def destroy
    @lookup.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lookup
      @lookup = Lookup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lookup_params
      params.require(:lookup).permit(:name, :content)
    end
end

app/helpers/lookups_helper.rb
module LookupsHelper
end

app/views/lookups/_content.html.erb
<div class="panel">
    <%= @content.html_safe %>
</div>
<p>
<% if admin_signed_in? %>
    <% if @lookup != nil %>
        <%= link_to 'Edit', edit_lookup_path(@lookup) %>
    <% else %>
        <%= link_to 'Create', new_lookup_path %>
    <% end %>
<% end %>
</p>

app/views/lookups/_form.html.erb
<%= form_for(@lookup) do |f| %>
  <% if @lookup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lookup.errors.count, "error") %> prohibited this lookup from being saved:</h2>

      <ul>
      <% @lookup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.cktext_area :content, rows: 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lookups/_helpform.html.erb
<style type="text/css">
  textarea { padding:2px; border:2px inset #ccc; width:40em; height:20em }
</style>

<%= form_tag(genhelp_contact_path) do -%>

  <%= label "from", "From" %>
  <%= text_field_tag('from')%>

  <%= label "subject", "Subject" %>
  <%= text_field_tag 'subject' %>

  <%= label "body", "Body" %>
  <%= text_area_tag 'body' %>

  <div><%= submit_tag 'Send' %></div>
  <div> <h3> <%= link_to "Back", contact_path %></h3> </div>
<% end -%>

app/views/lookups/contact.html.erb
<%= render "content" %>

app/views/lookups/edit.html.erb
<h1>Editing lookup</h1>

<%= render 'form' %>

<%= link_to 'Show', @lookup %> |
<%= link_to 'Back', lookups_path %>

app/views/lookups/genhelpform.html.erb
<style type="text/css">
  textarea { padding:2px; border:2px inset #ccc; width:40em; height:20em }
</style>
<h2>General questions</h2>

<%= render "helpform" %>

app/views/lookups/index.html.erb
<h1>Listing lookups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lookups.each do |lookup| %>
      <tr>
        <td><%= lookup.name %></td>
        <td><%= lookup.content %></td>
        <td><%= link_to 'Show', lookup %></td>
        <td><%= link_to 'Edit', edit_lookup_path(lookup) %></td>
        <td><%= link_to 'Destroy', lookup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lookup', new_lookup_path %>

app/views/lookups/main.html.erb
<%= render "content" %>

app/views/lookups/new.html.erb
<h1>New lookup</h1>

<%= render 'form' %>

<%= link_to 'Back', lookups_path %>

app/views/lookups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lookup.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @lookup.content %>
</p>

<%= link_to 'Edit', edit_lookup_path(@lookup) %> |
<%= link_to 'Back', lookups_path %>

app/views/lookups/techhelpform.html.erb
<style type="text/css">
  textarea { padding:2px; border:2px inset #ccc; width:40em; height:20em }
</style>
<h2>Technical questions</h2>

<%= render "helpform" %>