config/routes.rb
Newstemweb::Application.routes.draw do

  resources :posts

  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'
  resources :lookups

  root to: "lookups#main"
  match "runspedestem" => "runstem#index", :as => "runstem", :via => "get"
  match "runspedestem/subsampling" => "runstem#subsamplingform", :as => "subsamplingform", :via => "get"
  match "runspedestem/subsampling" => "runstem#subsampling", :as => "subsampling", :via => "post"
  match "runspedestem/generatesettings" => "runstem#generatesettingsform", :as => "generatesettingsform", :via => "get"
  match "runspedestem/generatesettings" => "runstem#generatesettings", :as => "generatesettings", :via => "post"
  match "runspedestem/discovery" => "runstem#discoveryform", :as => "discoveryform", :via => "get"
  match "runspedestem/discovery" => "runstem#discovery", :as => "discovery", :via => "post"

  match "runspedestem/validation" => "runstem#validationform", :as => "validationform", :via => "get"
  match "runspedestem/validation" => "runstem#validation", :as => "validation", :via => "post"

  
  match "runspedestem/cleantrees" => "runstem#cleantreesform", :as => "cleantreesform", :via => "get"
  match "runspedestem/cleantrees" => "runstem#cleantrees", :as => "cleantrees", :via => "post"

  match "/contact" => "lookups#contact", :as => "contact", :via => "get"

  match "contact/genhelp" => "lookups#genhelpform", :as => "genhelpform_contact", :via => "get"
  match "contact/genhelp" => "lookups#genhelp", :as => "genhelp_contact", :via => "post"

  match "contact/techhelp" => "lookups#techhelpform", :as => "techhelpform_contact", :via => "get"
  match "contact/techhelp" => "lookups#techhelp", :as => "techhelp_contact", :via => "post"

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:edit, :update, :destroy, :new, :create]

  def handle_lookup(name)
      @lookup = Lookup.where(name: name).first
      if @lookup
          @content = @lookup.content
      else
          @content = "<h3>"+ name + "</h3>"
      end
  end  
  # GET /posts
  # GET /posts.json
  def index
    handle_lookup "postsindex"
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.cktext_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render template: "lookups/_content" %>
<table>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <% if admin_signed_in? %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin_signed_in? %>
    <%= link_to 'New Post', new_post_path, class: "button" %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h3>  <%= @post.title %> </h3>

<%= @post.content.html_safe %>

<% if admin_signed_in? %>
    <%= link_to 'Edit', edit_post_path(@post), class: "button" %> 
    <%= link_to 'Back', posts_path, class: "button" %>
<% end %>