config/routes.rb
Newstemweb::Application.routes.draw do

  resources :posts

  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'
  resources :lookups

  root to: "lookups#main"
  match "runspedestem" => "runstem#index", :as => "runstem", :via => "get"
  match "runspedestem/subsampling" => "runstem#subsamplingform", :as => "subsamplingform", :via => "get"
  match "runspedestem/subsampling" => "runstem#subsampling", :as => "subsampling", :via => "post"
  match "runspedestem/generatesettings" => "runstem#generatesettingsform", :as => "generatesettingsform", :via => "get"
  match "runspedestem/generatesettings" => "runstem#generatesettings", :as => "generatesettings", :via => "post"
  match "runspedestem/discovery" => "runstem#discoveryform", :as => "discoveryform", :via => "get"
  match "runspedestem/discovery" => "runstem#discovery", :as => "discovery", :via => "post"

  match "runspedestem/validation" => "runstem#validationform", :as => "validationform", :via => "get"
  match "runspedestem/validation" => "runstem#validation", :as => "validation", :via => "post"

  
  match "runspedestem/cleantrees" => "runstem#cleantreesform", :as => "cleantreesform", :via => "get"
  match "runspedestem/cleantrees" => "runstem#cleantrees", :as => "cleantrees", :via => "post"

  match "/contact" => "lookups#contact", :as => "contact", :via => "get"

  match "contact/genhelp" => "lookups#genhelpform", :as => "genhelpform_contact", :via => "get"
  match "contact/genhelp" => "lookups#genhelp", :as => "genhelp_contact", :via => "post"

  match "contact/techhelp" => "lookups#techhelpform", :as => "techhelpform_contact", :via => "get"
  match "contact/techhelp" => "lookups#techhelp", :as => "techhelp_contact", :via => "post"

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50086712-2', 'osu.edu');
  ga('send', 'pageview');

</script>

app/views/layouts/_back.html.erb
<%= link_to "Go Back","#", onclick: "javascript:window.history.back(-1);return false;", class: "button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "SpedeSTEM" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <div class="row">
          <div class="small-2 columns"></div>
          <div class="small-10 columns">
              <nav class="top-bar" data-topbar>
                  <ul class="title-area">
                      <li class="name">
                      <h1><a href="/">SpedeSTEM</a></h1>
                      </li>
                      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
                  </ul>

                  <section class="top-bar-section">

                      <!-- Left Nav Section -->
                      <ul class="left">
                              <li>
                                <%= link_to "Run SpedeSTEM", runstem_path %> 
                              </li>
                              <li>
                                <%= link_to "Resources", posts_path %> 
                              </li>
                              <li>
                                <%= link_to "Contact", contact_path %> 
                              </li>
                      </ul>

                      <!-- Right Nav Section -->
                      <ul class="right">

                            <% if admin_signed_in? %>
                              <li class="active"> 
                              <%= link_to "Sign out", 
                                  destroy_admin_session_path, :method => :delete %> 
                              </li>
                            <% else %>
                              <li class="active"> 
                              <%= link_to "Sign in", new_admin_session_path%> 
                              </li>
                            <% end %>
                      </ul>
                  </section>
              </nav>
          </div>
      </div>

      <div class="row">
          <div class="small-2 columns"></div>
          <div class="small-10 columns">
            </br>
            <%= render template: "partials/_flash" %>
            </br>
            <%= yield %>
          </div>
      </div>



    <div class="row">
      <div class="small-1 small-offset-2 columns">
        <%= link_to(image_tag("/assets/logo-tosusquare-flat.png"), "http://www.osu.edu" )%>
      </div>
      <div class="small-4 columns">
      Department of Ecology Evolution and Organismal Biology
      </div>
      <div class="small-5 columns"></div>
    </div>

    <div class="row">
      <div class="small-4 small-offset-2 columns">
      <%= link_to(image_tag("/assets/nsf.png"), "http://www.nsf.gov") %>
      </div>
      <div class="small-6 columns"></div>
    </div>
    
    <div class="row">
      <div class="small-3 small-offset-2 columns">
        Funded by NSF DEB 0918212 
      </div>
      <div class="small-8 columns"></div>
    </div>


    <%= render template: "layouts/_analytics" %>
    <%= javascript_include_tag "application" %>
  </body>
</html>